

<div class="form-group">
    <div class="col-lg-3">
        <button class="btn btn-default form-control" type="button" onclick="abreFormulario('criar');">Criar</button>
    </div>
    <div class="col-lg-3">
        <button class="btn btn-default form-control" type="button" onclick="abreFormulario('listar');">Listar</button>
    </div>
    <div class="col-lg-3">
        <button class="btn btn-default form-control" type="button" onclick="testar();">Teste</button>
    </div>
</div>

<div class="modal fade" id="criar">
    <div class="modal-dialog  modal-lg">
        <form class="form-horizontal" method="post" id="frmCriar" action="<?= $this->link('/criadorcarta/cadastrar'); ?>">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Criar Carta</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-lg-12">
                            <div class="col-lg-8">
                                <label class="label label-primary" for="nome">
                                    Nome
                                </label>
                                <input name="nome" id="nome" class="form-control input-sm"/>
                            </div>
                            <div class="col-lg-2">
                                <label class="label label-primary" for="ataque">
                                    Ataque
                                </label>
                                <input name="ataque" id="ataque" class="form-control input-sm"/>
                            </div>
                            <div class="col-lg-2">
                                <label class="label label-primary" for="defesa">
                                    Defesa
                                </label>
                                <input name="defesa" id="defesa" class="form-control input-sm"/>
                            </div>
                            <div class="col-lg-12">
                                <label class="label label-primary" for="descricao">
                                    Descrição
                                </label>
                                <textarea name="descricao" id="descricao" class="form-control" placeholder="Descrição dessa carta"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer bg-success">
                    <div class="row">
                        <div class="col-lg-2">
                            <button class="btn btn-default form-control" type="button" onclick="cadastrarCarta();">Cadastrar</button>
                        </div>
                        <div class="col-lg-2">
                            <button class="btn btn-default form-control" type="button" onclick="limpaFormulario();">Limpar</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="listar">
    <div class="modal-dialog  modal-lg">
        <form class="form-horizontal" method="post" id="frmListar" action="<?= $this->link('/criadorcarta/listar'); ?>">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Listar Carta</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-lg-12">
                            <div class="col-lg-8">
                                <label class="label label-primary" for="nome">
                                    Nome
                                </label>
                                <input name="nome" id="nome" class="form-control input-sm"/>
                            </div>
                            <div class="col-lg-2">
                                <label class="label label-primary" for="ataque">
                                    Ataque
                                </label>
                                <input name="ataque" id="ataque" class="form-control input-sm"/>
                            </div>
                            <div class="col-lg-2">
                                <label class="label label-primary" for="defesa">
                                    Defesa
                                </label>
                                <input name="defesa" id="defesa" class="form-control input-sm"/>
                            </div>
                            <table class="table table-striped table-condensed table-bordered table-hover table-responsive">
                                <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th>Ataque</th>
                                        <th>Defesa</th>
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="modal-footer bg-success">
                    <div class="row">
                        <div class="col-lg-2">
                            <button class="btn btn-default form-control" type="button" onclick="listarCarta();">Consultar</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

