
<div class="panel panel-default">
    <div class="panel-heading text-center">
        <span class="glyphicon glyphicon-asterisk"></span> Cadastrar Carta
    </div>
    <form class="form-horizontal" method="post" id="frmCriar" action="<?= $this->link('/criadorcarta/cadastrar'); ?>">
        <div class="panel-body">

            <div class="row">
                <div class="form-group col-lg-12">
                    <div class="col-lg-8">
                        <label class="label label-primary" for="nome">
                            Nome
                        </label>
                        <input name="nome" id="nome" class="form-control"/>
                    </div>
                    <div class="col-lg-2">
                        <label class="label label-primary" for="ataque">
                            Ataque
                        </label>
                        <input name="ataque" id="ataque" class="form-control"/>
                    </div>
                    <div class="col-lg-2">
                        <label class="label label-primary" for="defesa">
                            Defesa
                        </label>
                        <input name="defesa" id="defesa" class="form-control"/>
                    </div>
                    <div class="col-lg-12">
                        <label class="label label-primary" for="descricao">
                            Descrição
                        </label>
                        <textarea name="descricao" id="descricao" class="form-control" placeholder="Descrição dessa carta"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-lg-2">
                    <button class="btn btn-default form-control" type="button" onclick="cadastrarCarta();">Cadastrar</button>
                </div>
                <div class="col-lg-2">
                    <button class="btn btn-default form-control" type="button" onclick="limpaFormulario();">Limpar</button>
                </div>
            </div>
        </div>
    </form>
</div>

