<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-header">
            <span class="panel-title">Usuarios</span>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-2">
                <a href="<?= $this->link('/usuario/cadastro'); ?>" class="btn btn-info form-control">Novo</a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-condensed table-responsive table-striped table-hover">
                    <thead class="bg-info">
                        <tr>
                            <th>
                                Id
                            </th>
                            <th>
                                Nome
                            </th>
                            <th>
                                Adm
                            </th>
                            <th>
                                Ativo
                            </th>
                            <th class="text-center">
                                Ação
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->view->lista as $usuario) {
                            echo "<tr><td>{$usuario->getUsuario()}</td><td>{$usuario->getNome()}</td>"
                            . "<td>{$usuario->getAdministrador()}</td>"
                            . "<td>{$usuario->getAtivo()}</td>"
                            . "<td class='text-center'><a href='#' onclick='editar({$usuario->getUsuario()});' class='glyphicon glyphicon-pencil'></a>"
                            . "<a href='#' onclick='excluir({$usuario->getUsuario()});' class='glyphicon glyphicon-trash'></a></td></tr>";
                        }
                        ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<?= $this->parteRender('base/dialog'); ?>
<input id="acao_excluir" type="hidden" value="<?= $this->link('/usuario/excluir') ?>"/>
<input id="acao_editar" type="hidden" value="<?= $this->link('/usuario/cadastro') ?>"/>
<input id="men_editar" type="hidden" value="Editar Usuário?"/>
<input id="men_excluir" type="hidden" value="Excluir Usuário?"/>