<div class="panel panel-info">
    <div class="panel-heading">
        <div class="panel-header">
            <span class="panel-title">Usuarios</span>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-2">
                <a href="<?= $this->link('/usuario/cadastro'); ?>" class="btn btn-info form-control">Novo</a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-condensed table-responsive table-striped table-hover">
                    <thead class="bg-danger">
                        <tr>
                            <th>
                                Id
                            </th>
                            <th>
                                Nome
                            </th>
                            <th>
                                Adm
                            </th>
                            <th>
                                Ativo
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->view->usuarios as $usuario) {
                            echo "<tr><td>{$usuario->getUsuario()}</td><td>{$usuario->getNome()}</td>" .
                            "<td>{$usuario->getAdministrador()}</td>" .
                            "<td>{$usuario->getAtivo()}</td></tr>";
                        }
                        ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

