<form class="form-horizontal" id="form" action="<?= $this->link('/equipamento/salvar'); ?>" method="POST">
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="panel-title">Cadastro de Equipamento</span>
        </div>
        <div class="panel-body">
            <div class="row">
                <input type="hidden" name="usuario" id="id">
                <div class="col-lg-3">
                    <span class="label label-default">Número de Serie</span>
                    <input type="text" id="numero_serie" name="numeroSerie" class="form-control" required="true" placeholder="ex: 1231231A32-1">
                </div>
                <div class="col-lg-5">
                    <span class="label label-default">Descrição</span>
                    <input type="text" id="descricao" name="descricao" class="form-control" required="true" placeholder="ex: notebook cce">
                </div>
                <div class="col-lg-4">
                    <span class="label label-default">Modelo</span>
                    <input type="text" id="modelo" name="modelo" class="form-control" required="true" placeholder="ex: ASPIRE 4740">
                </div>
                <div class="col-lg-4">
                    <span class="label label-default">Marca</span>
                    <select class="form-control" id="marca" name="marca" required="true">
                        <?php
                        foreach ($this->view->marcas as $marca) {
                            echo "<option value='{$marca->getId()}'>{$marca->getNome()}</option>";
                        }
                        ?>
                    </select>
                </div>
                <div class="col-lg-4">
                    <span class="label label-default">Grupo</span>
                    <select class="form-control" id="grupo" name="grupo" required="true">
                        <?php
                        foreach ($this->view->grupos as $grupo) {
                            echo "<option value='{$grupo->getId()}'>{$grupo->getNome()}</option>";
                        }
                        ?>
                    </select>
                </div>

                <div class="col-lg-12">
                    <span class="label label-default">Observaçoes</span>
                    <textarea name="observacoes" id="observacoe" class="form-control"></textarea>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-bordered table-hover table-striped ">
                    <thead class="row">
                        <tr>

                        </tr>
                    </thead>
                    <tbody id="acessorios" class="row">

                    </tbody>
                </table>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-lg-3">
                    <button type="button" id="btnAdd" class="btn btn-primary form-control">Adicionar Acessório</button>
                </div>
                <div class="col-lg-3">
                    <button type="submit" class="btn btn-success form-control">Salvar</button>
                </div>
                <div class="col-lg-3">
                    <a href="<?= $this->link('/equipamento'); ?>" class="btn btn-danger form-control">Cancelar</a>
                </div>
            </div>
        </div>
    </div>
</form>


<div class="modal fade" id="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-center"><span>Adicionar Acessório</span></h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-8">
                        <label class="label label-info">Descrição da Propriedade</label>
                        <input class="form-control" id="nome_prop" placeholder="ex: HDD 500G ou Memoria 4G" required="true"/>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="form-group">
                        <div class="col-lg-4">
                            <button class="btn btn-primary form-control" id="btnOk">Incluir</button>
                        </div>
                        <div class="col-lg-4">
                            <button class="btn btn-danger form-control" onclick="$('#dialog').modal('hide');">Terminei</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

