<div class="panel panel-info">
    <div class="panel-heading">
        <div class="panel-header">
            <span class="panel-title">Equipamentos Cadastrados</span>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-2">
                <a href="<?= $this->link('/equipamento/cadastro'); ?>" class="btn btn-info form-control">Novo</a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-condensed table-responsive table-striped table-hover">
                    <thead class="bg-danger">
                        <tr>
                            <th>
                                Nº Série
                            </th>
                            <th>
                                Descrição
                            </th>
                            <th>
                                Modelo
                            </th>
                            <th>
                                Marca
                            </th>
                            <th>
                                Grupo
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->view->equipamentos as $equipa) {
                            echo "<tr><td>{$equipa->getNumeroSerie()}</td>"
                            . "<td>{$equipa->getDescricao()}</td>"
                            . "<td>{$equipa->getModelo()}</td>"
                            . "<td>{$equipa->getMarca()}</td>"
                            . "<td>{$equipa->getGrupo()}</td></tr>";
                        }
                        ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

