<div class="row">
    <div class="col-lg-12">
        <table class="table table-condensed table-responsive">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Nome
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->view->marcas as $marca) {
                    echo "<tr><td>{$marca->getId()}</td><td>{$marca->getNome()}</td></tr>";
                }
                ?>

            </tbody>
        </table>
    </div>
</div>

