<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-header">
            <span class="panel-title">Marcas</span>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-2">
                <a href="<?= $this->link('/marca/cadastro'); ?>" class="btn btn-info form-control">Novo</a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-condensed table-responsive table-striped table-hover">
                    <thead>
                        <tr class="bg-info">
                            <th>
                                Id
                            </th>
                            <th>
                                Nome
                            </th>
                            <th class="text-center">
                                Ação
                            </th>
                        </tr >
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->view->lista as $marca) {
                            echo "<tr><td>{$marca->getId()}</td><td>{$marca->getNome()}</td>";
                            echo "<td class='text-center'><a href='#' onclick='editar({$marca->getId()});' class='glyphicon glyphicon-pencil'></a>";
                            echo "<a href='#' onclick='excluir({$marca->getId()});' class='glyphicon glyphicon-trash'></a></td></tr>";
                        }
                        ?>

                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
<?= $this->parteRender('base/dialog'); ?>
<input id="acao_excluir" type="hidden" value="<?= $this->link('/marca/excluir') ?>"/>
<input id="acao_editar" type="hidden" value="<?= $this->link('/marca/cadastro') ?>"/>
<input id="men_editar" type="hidden" value="Editar Marca?"/>
<input id="men_excluir" type="hidden" value="Excluir Marca?"/>