
<form class="form-horizontal" id="form">
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="panel-title">Cadastro de Marca</span>
        </div>
        <div class="panel-body">
            <div class="row">
                <input type="hidden" name="id" id="id">
                <div class="col-lg-3">
                    <span class="label label-default">Nome</span>
                    <input type="text" id="nome" name="nome" class="form-control" required="true">
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-lg-3">
                    <button type="button" class="btn btn-default form-control" onclick="executar();">Salvar</button>
                </div>
            </div>
        </div>
    </div>
</form>


