
<div class="panel panel-default" style="margin: 0 auto; width: 300px;">
    <div class="panel-heading text-center">
        <span class="glyphicon glyphicon-camera"></span> Identifique-se
    </div>
    <div class="panel-body">
        <div class="row">
            <form class="form-horizontal" method="post" action="<?= $this->link('/cardgame/registro') ?>">
                <div class="form-group col-lg-12">
                    <div class="col-lg-12">
                        <label>Nome</label>
                        <input class="form-control" name="player" placeholder="Nome"/>
                    </div>
                </div>
                <div class="form-group col-lg-12">
                    <div class="col-lg-12">
                        <button class="form-control btn btn-primary">OK</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>