<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-header">
            <span class="panel-title">Grupos</span>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-2">
                <a href="<?= $this->link('/grupo/cadastro'); ?>" class="btn btn-info form-control">Novo</a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-condensed table-responsive table-striped table-hover">
                    <thead>
                        <tr class="bg-info">
                            <th>
                                Id
                            </th>
                            <th>
                                Nome
                            </th>
                            <th>
                                Descrição
                            </th>
                            <th class="text-center">
                                Ação
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->view->lista as $grupo) {
                            echo "<tr><td>{$grupo->getId()}</td><td>{$grupo->getNome()}</td><td>{$grupo->getDescricao()}</td>"
                            . "<td class='text-center'><a href='#' onclick='editar({$grupo->getId()});' class='glyphicon glyphicon-pencil'></a>"
                            . "<a href='#' onclick='excluir({$grupo->getId()});' class='glyphicon glyphicon-trash'></a></td></tr>";
                        }
                        ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<?= $this->parteRender('base/dialog'); ?>
<input id="acao_excluir" type="hidden" value="<?= $this->link('/grupo/excluir') ?>"/>
<input id="acao_editar" type="hidden" value="<?= $this->link('/grupo/cadastro') ?>"/>
<input id="men_editar" type="hidden" value="Editar Grupo?"/>
<input id="men_excluir" type="hidden" value="Excluir Grupo?"/>
