<form class="form-horizontal" id="form" action="<?= $this->link('/grupo/salvar'); ?>" method="POST">
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="panel-title">Cadastro de Grupo</span>
        </div>
        <div class="panel-body">
            <div class="row">
                <input type="hidden" name="id_objeto" id="id" value="<?= $this->escreve("objeto", "getId"); ?>"/>
                <div class="col-lg-3">
                    <span class="label label-default">Nome</span>
                    <input type="text" id="nome" name="nome" class="form-control" value="<?= $this->escreve("objeto", "getNome"); ?>"  required="true"/>
                </div>
                <div class="col-lg-3">
                    <span class="label label-default">Descrição</span>
                    <input type="text" id="descricao" name="descricao" class="form-control" value="<?= $this->escreve("objeto", "getDescricao"); ?>" required="true"/>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-lg-3">
                    <button type="submit" class="btn btn-success form-control">Salvar</button>
                </div>
                <div class="col-lg-3">
                    <a href="<?= $this->link('/grupo'); ?>" class="btn btn-danger form-control">Cancelar</a>
                </div>
            </div>
        </div>
    </div>
</form>
