<!DOCTYPE html>
<html>
    <header>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>SistemaOS - Firetech</title>
        <?= $this->css('bootstrap-theme.min'); ?>
        <?= $this->css('bootstrap.min'); ?>
        <?= $this->css('padrao'); ?>
    </header>

    <body>
        <div class="navbar navbar-inverse" role="navigation">
            <ul class="nav navbar-nav">
                <li><a href="<?= $this->link(""); ?>"><span class="glyphicon glyphicon-globe"></span> <span class="h4">SistemaOS</span></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Cadastros Básicos<b class="caret"></b></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?= $this->link("/marca"); ?>"><span>Marca</span></a></li>
                        <li><a href="<?= $this->link("/grupo"); ?>"><span>Grupo</span></a></li>
                        <li><a href="<?= $this->link("/usuario"); ?>"><span>Usuário</span></a></li>
                        <li><a href="<?= $this->link("/equipamento"); ?>"><span>Equipamento</span></a></li>
                    </ul>
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col-lg-10">
                <?php $this->content(); ?>;
            </div>
        </div>
        <div class="modal fade modal_info">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header" id="men-tipo">
                        <h3 class="modal-title text-center"><span id="men-titulo"></span></h3>
                    </div>
                    <div class="modal-body">
                        <div id="men-informacao"></div>
                    </div>
                    <div class="modal-footer">
                        <div class="row">
                            <div class="form-group">
                                <div class="col-lg-4">
                                    <button class="btn btn-primary form-control" onclick="$('.modal_info').modal('hide');">OK</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="erro"></div>
        <?= $this->js('jquery-1.10.2.min'); ?><br/>
        <?= $this->js('bootstrap'); ?><br/>
        <?= $this->js('functions'); ?><br/>
        <?php $this->scripts(); ?><br/>
    </body>
</html>